package com.angel.gg.export

import java.time.LocalDate
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class DeflateXlsxTest {

    @Test
    fun leeXlsxDeflateReguardadoPorExcel() {
        val bytes = decodificarBase64(FIXTURE)
        val resultado = ImportarXlsx.leer(bytes)
        assertTrue(
            resultado is ImportarXlsx.ResultadoLectura.Ok,
            "un xlsx Deflate (reguardado por Excel) debe leerse, no reportarse vacio"
        )
        val datos = resultado.datos

        assertEquals(3, datos.filas.size)
        val primera = datos.filas[0]
        assertEquals(31666.67, primera.monto, 0.001)
        assertEquals("Cuota Celular", primera.descripcion)
        assertEquals("Cuotas", primera.categoriaNombre)
        assertEquals(LocalDate.of(2026, 9, 10), primera.fecha)
        assertTrue(primera.esCuota)

        val ultima = datos.filas[2]
        assertEquals(100000.0, ultima.monto, 0.001)
        assertEquals("Pago mensual", ultima.descripcion)
        assertEquals("Departamento", ultima.categoriaNombre)
        assertTrue(!ultima.esCuota)

        assertEquals(1, datos.ingresosPorMes.size)
        val ingreso = datos.ingresosPorMes[0]
        assertEquals(1000000.0, ingreso.monto, 0.001)
        assertEquals(2026, ingreso.anio)
        assertEquals(9, ingreso.mes)
    }

    private fun decodificarBase64(s: String): ByteArray {
        val alfabeto = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
        val valores = IntArray(128) { -1 }
        alfabeto.forEachIndexed { i, c -> valores[c.code] = i }
        var acc = 0
        var bits = 0
        val out = ArrayList<Byte>()
        for (c in s) {
            if (c == '\n' || c == '\r' || c == ' ' || c == '=') continue
            acc = (acc shl 6) or valores[c.code]
            bits += 6
            if (bits >= 8) {
                bits -= 8
                out.add(((acc shr bits) and 0xFF).toByte())
            }
        }
        return out.toByteArray()
    }

    companion object {
        private val FIXTURE = """        UEsDBBQABgAIAAAAIQCtStNnbAEAABAFAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACslE1OwzAQ
        hfdI3CHyFiVuWSCEmnZRYAmVKAcw9qSx6tiWxy3t7Zm4P0KopKBmEyu2530vbxyPJpvGZGsIqJ0t2bAYsAysdErbRcne58/5
        PcswCquEcRZKtgVkk/H11Wi+9YAZVVssWR2jf+AcZQ2NwMJ5sLRSudCISK9hwb2QS7EAfjsY3HHpbAQb89hqsPHoESqxMjF7
        2tD0zkkAgyyb7ja2rJIJ742WIpJTvrbqByXfEwqqTHuw1h5vyAbjJwntyu+Afd0rRRO0gmwmQnwRDdngG8M/XVh+OLcsukVO
        uHRVpSUoJ1cNJVCgDyAU1gCxMUUai0Zoe/B9ik/Fs+A8UowB/u/gkFNbnXsSghA1HJPqJFILLv5kaJusQP2RvU87RYM8DcOe
        Y2+7mYS7UicfkU437J6XW0hiZ4AYtwaw70OWRM+RaxFAvcVA90DvBr5rn/EhhZHTmn6InkM46h74PN1n4y8AAAD//wMAUEsD
        BBQABgAIAAAAIQC1VTAj9AAAAEwCAAALAAgCX3JlbHMvLnJlbHMgogQCKKAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArJJNT8MwDIbvSPyHyPfV3ZAQ
        Qkt3QUi7IVR+gEncD7WNoyQb3b8nHBBUGoMDR3+9fvzK2908jerIIfbiNKyLEhQ7I7Z3rYaX+nF1ByomcpZGcazhxBF21fXV
        9plHSnkodr2PKqu4qKFLyd8jRtPxRLEQzy5XGgkTpRyGFj2ZgVrGTVneYviuAdVCU+2thrC3N6Dqk8+bf9eWpukNP4g5TOzS
        mRXIc2Jn2a58yGwh9fkaVVNoOWmwYp5yOiJ5X2RswPNEm78T/XwtTpzIUiI0Evgyz0fHJaD1f1q0NPHLnXnENwnDq8jwyYKL
        H6jeAQAA//8DAFBLAwQUAAYACAAAACEAZN+UGowDAAD2CAAADwAAAHhsL3dvcmtib29rLnhtbKxVbW+bOhT+Pun+B8R3CjYv
        IajpFN50K7VVlGbtJkWaXDAFFTAzpkk17b/vGELaLNOU212UmNg+PH7OOc9Dzj9uq1J5prwtWD1T0ZmhKrROWFrUjzP10yrW
        XFVpBalTUrKaztQX2qofL/75cL5h/OmBsScFAOp2puZCNJ6ut0lOK9KesYbWsJMxXhEBU/6otw2nJG1zSkVV6tgwHL0iRa0O
        CB4/BYNlWZHQkCVdRWsxgHBaEgH027xo2hGtSk6Bqwh/6hotYVUDEA9FWYiXHlRVqsS7fKwZJw8lpL1FtrLl8HHgiwwY8HgS
        bB0dVRUJZy3LxBlA6wPpo/yRoSN0UILtcQ1OQ7J0Tp8L2cM9K+68k5Wzx3JewZDx12gIpNVrxYPivRPN3nPD6sV5VpT0bpCu
        QprmhlSyU6WqlKQVUVoIms7UCUzZhh4s8K7xu6KEXdOwDazqF3s5L7iS0ox0pViBkEd4cIbjTLEtI0EY81JQXhNBA1YL0OEu
        r7/VXI8d5AwUrizpt67gFIwF+oJcYSSJRx7aBRG50vFypobeWpoQnLrekCQh4Lx1sECLaBEbcFkGDtbR5yC6Cm7u1iZ1LBMT
        qrmpmWhW4mDNtVyqTa3MtGxsWpmN128kTY798x9ETRJZKR1KNaQz/P61bJAV90bhLgRX4PdleAXNuyXP0EoQTLpz+iX0yv36
        HeFpEPgx0uKJE2iWgSLNNyOsYRvhCLlTNLfjH5AFd7yEkU7kO3lIzJlqgRaOtq7JdtxBhtcV6ev532UZ5aX9Zhj3fshM5Yvw
        rqCb9lVIcqps74s6ZZuZqjmQzMvBbNNv3RepyEFetuVCxLD2Ly0ec+CLkGNJ03Asec3UAz7hQCqGS5PDAR/9DaH+hQvE+rtS
        9ya5pY2CDQwG71dldZGqcE+ewi9T1HdvfDAhZQK2kLc+cIoM7MoIuhVXrejvoMgCCCLLmE+MqaUZkWlrljuVKjOxFlghjuxJ
        FEa+Lfsj/zK8/+PF2RvDG/+LJMuccLHiJJG+WNLMJy0oaUgI+L4l69uub5hA0YpRrFloami+71iaHcamPUFhEA1iGsjK9LN3
        vrZcvX+aEtGBpaWb+7knx3i3ul/MhoVdpw5M5y1DWffd038KvIXsS3picHx3YmBwc726PjH2Klp9vY9PDZ5f++H89Pj5cjn/
        soo+j0fovy2o3jdcjr1M9VEmFz8BAAD//wMAUEsDBBQABgAIAAAAIQCSB5TsBAEAAD8DAAAaAAgBeGwvX3JlbHMvd29ya2Jv
        b2sueG1sLnJlbHMgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACskstqxDAMRfeF/oPR
        vnEyfVCGcWbRUphtm36AcJQ4TGIHW33k72tSOsnAkG6yMUjC9x6Ju9t/d634JB8aZxVkSQqCrHZlY2sF78XLzSOIwGhLbJ0l
        BQMF2OfXV7tXapHjp2CaPoioYoMCw9xvpQzaUIchcT3ZOKmc75Bj6WvZoz5iTXKTpg/SzzUgP9MUh1KBP5S3IIqhj87/a7uq
        ajQ9O/3RkeULFjLw0MYFRIG+JlbwWyeREeRl+82a9hzPQpP7WMrxzZYYsjUZvpw/BkPEE8epFeQ4WYS5XxNGY6ufDDZ2gjm1
        li5yt2ooDHoq39jHzM+zMW//wciz2Oc/AAAA//8DAFBLAwQUAAYACAAAACEAYndpzUIDAACXCQAAGAAAAHhsL3dvcmtzaGVl
        dHMvc2hlZXQxLnhtbJxWXW+bMBR9n7T/gHjaHgKYAPlQkipNmiUPlaZ13Z4dYhKrgJFxPqpp/33XNhACK6papTjY5xz7nntt
        Z3J3SWLjRHhOWTo1keWYBklDtqPpfmo+/1z1hqaRC5zucMxSMjVfSW7ezT5/mpwZf8kPhAgDFNJ8ah6EyMa2nYcHkuDcYhlJ
        YSRiPMECXvnezjNO8E6Rkth2HSewE0xTUyuM+Xs0WBTRkCxZeExIKrQIJzEWsP78QLO8VEvC98glmL8cs17IkgwktjSm4lWJ
        mkYSjjf7lHG8jSHuC/JwaFw4fFz475fTqP7WTAkNOctZJCxQtvWa2+GP7JGNw0qpHf+7ZJBnc3KiMoFXKfdjS0J+peVexfof
        FAsqMWkXHx/pbmr+cYq/HrRIPpzroxz7a84mOwoZllEZnERTc47GG8+0ZxNVP78oOee174bA2ycSk1AQmAOZhizPLWMvEriB
        LkdS7RZ3pcrzOzd2JMLHWCxY/JvuxAE0kOW5/mCIXN8sR3+w85rQ/UHAsC8FQxbDKuBpJFRuH6gafNHzFypgY3jMBUtK2YKm
        CTCqCNCeNcF1LHfoIz+Q03YwwVHFhLZgItipHQSvIIBsSehe26AgQFsSQKNjhlFBgLZzSbZ2TeViiQWeTTg7G1D9YF+eYXmW
        oDGIKJtda+BDMYRyfC4BCgYJyKH3NHMm9gnyGhaI+zYC3SIWbYR7i1i2Ef1bxEMb4d0iVhrhqmTLpX9rU/xbyrpJ2bQpQUWx
        wbLKN8hjt28SIH2TjvVREARWMGgYV0KMytoGYqERUG8VYtgwTiM8NY0XuINGhA9thVHDNo2o2VZfOdKnQ8O2JmVzpUSzb27v
        6fnxy3w8/zqxIxn+0Bv5gW+ha0pvrITwuq2UgNJKNBwEQ6tRPvcl4uoTalTpQkO6rNSIt61sK6BGoa805OrlutZxEzPs6u6Y
        JaCKWSWhUTwloBZyw5WFhtRDrqVA7e6lhrwdsx6/BrRqdqxrHTpCfeDrQwYfBVvRWBBeXSgPQPjvvTR6816CQz/De/KI+Z6m
        uRGTCLaDY8EhyfXFoL4LlqleOGy3TMDpX74d4AcQgfPAscCKiDFYjX6Rt1P1k2r2DwAA//8DAFBLAwQUAAYACAAAACEAwRcQ
        vk4HAADGIAAAEwAAAHhsL3RoZW1lL3RoZW1lMS54bWzsWc2LGzcUvxf6Pwxzd/w1448l3uDPbJPdJGSdlBy1tuxRVjMykrwb
        EwIlOfVSKKSll0JvPZTSQAMNvfSPCSS06R/RJ83YI63lJJtsSlp2DYtH/r2np/eefnrzdPHSvZh6R5gLwpKWX75Q8j2cjNiY
        JNOWf2s4KDR8T0iUjBFlCW75Cyz8S9uffnIRbckIx9gD+URsoZYfSTnbKhbFCIaRuMBmOIHfJozHSMIjnxbHHB2D3pgWK6VS
        rRgjkvhegmJQe30yISPsDZVKf3upvE/hMZFCDYwo31eqsSWhsePDskKIhehS7h0h2vJhnjE7HuJ70vcoEhJ+aPkl/ecXty8W
        0VYmROUGWUNuoP8yuUxgfFjRc/LpwWrSIAiDWnulXwOoXMf16/1av7bSpwFoNIKVprbYOuuVbpBhDVD61aG7V+9Vyxbe0F9d
        s7kdqo+F16BUf7CGHwy64EULr0EpPlzDh51mp2fr16AUX1vD10vtXlC39GtQRElyuIYuhbVqd7naFWTC6I4T3gyDQb2SKc9R
        kA2r7FJTTFgiN+VajO4yPgCAAlIkSeLJxQxP0AiyuIsoOeDE2yXTCBJvhhImYLhUKQ1KVfivPoH+piOKtjAypJVdYIlYG1L2
        eGLEyUy2/Cug1TcgL549e/7w6fOHvz1/9Oj5w1+yubUqS24HJVNT7tWPX//9/RfeX7/+8OrxN+nUJ/HCxL/8+cuXv//xOvWw
        4twVL7598vLpkxffffXnT48d2tscHZjwIYmx8K7hY+8mi2GBDvvxAT+dxDBCxJJAEeh2qO7LyAJeWyDqwnWw7cLbHFjGBbw8
        v2vZuh/xuSSOma9GsQXcY4x2GHc64Kqay/DwcJ5M3ZPzuYm7idCRa+4uSqwA9+czoFfiUtmNsGXmDYoSiaY4wdJTv7FDjB2r
        u0OI5dc9MuJMsIn07hCvg4jTJUNyYCVSLrRDYojLwmUghNryzd5tr8Ooa9U9fGQjYVsg6jB+iKnlxstoLlHsUjlEMTUdvotk
        5DJyf8FHJq4vJER6iinz+mMshEvmOof1GkG/CgzjDvseXcQ2kkty6NK5ixgzkT122I1QPHPaTJLIxH4mDiFFkXeDSRd8j9k7
        RD1DHFCyMdy3CbbC/WYiuAXkapqUJ4j6Zc4dsbyMmb0fF3SCsItl2jy22LXNiTM7OvOpldq7GFN0jMYYe7c+c1jQYTPL57nR
        VyJglR3sSqwryM5V9ZxgAWWSqmvWKXKXCCtl9/GUbbBnb3GCeBYoiRHfpPkaRN1KXTjlnFR6nY4OTeA1AuUf5IvTKdcF6DCS
        u79J640IWWeXehbufF1wK35vs8dgX9497b4EGXxqGSD2t/bNEFFrgjxhhggKDBfdgogV/lxEnatabO6Um9ibNg8DFEZWvROT
        5I3Fz4myJ/x3yh53AXMGBY9b8fuUOpsoZedEgbMJ9x8sa3pontzAcJKsc9Z5VXNe1fj/+6pm014+r2XOa5nzWsb19vVBapm8
        fIHKJu/y6J5PvLHlMyGU7ssFxbtCd30EvNGMBzCo21G6J7lqAc4i+Jo1mCzclCMt43EmPycy2o/QDFpDZd3AnIpM9VR4Myag
        Y6SHdSsVn9Ct+07zeI+N005nuay6mqkLBZL5eClcjUOXSqboWj3v3q3U637oVHdZlwYo2dMYYUxmG1F1GFFfDkIUXmeEXtmZ
        WNF0WNFQ6pehWkZx5QowbRUVeOX24EW95YdB2kGGZhyU52MVp7SZvIyuCs6ZRnqTM6mZAVBiLzMgj3RT2bpxeWp1aaq9RaQt
        I4x0s40w0jCCF+EsO82W+1nGupmH1DJPuWK5G3Iz6o0PEWtFIie4gSYmU9DEO275tWoItyojNGv5E+gYw9d4Brkj1FsXolO4
        dhlJnm74d2GWGReyh0SUOlyTTsoGMZGYe5TELV8tf5UNNNEcom0rV4AQPlrjmkArH5txEHQ7yHgywSNpht0YUZ5OH4HhU65w
        /qrF3x2sJNkcwr0fjY+9AzrnNxGkWFgvKweOiYCLg3LqzTGBm7AVkeX5d+JgymjXvIrSOZSOIzqLUHaimGSewjWJrszRTysf
        GE/ZmsGh6y48mKoD9r1P3Tcf1cpzBmnmZ6bFKurUdJPphzvkDavyQ9SyKqVu/U4tcq5rLrkOEtV5Srzh1H2LA8EwLZ/MMk1Z
        vE7DirOzUdu0MywIDE/UNvhtdUY4PfGuJz/IncxadUAs60qd+PrK3LzVZgd3gTx6cH84p1LoUEJvlyMo+tIbyJQ2YIvck1mN
        CN+8OSct/34pbAfdStgtlBphvxBUg1KhEbarhXYYVsv9sFzqdSoP4GCRUVwO0+v6AVxh0EV2aa/H1y7u4+UtzYURi4tMX8wX
        teH64r5c2Xxx7xEgnfu1yqBZbXZqhWa1PSgEvU6j0OzWOoVerVvvDXrdsNEcPPC9Iw0O2tVuUOs3CrVyt1sIaiVlfqNZqAeV
        Sjuotxv9oP0gK2Ng5Sl9ZL4A92q7tv8BAAD//wMAUEsDBBQABgAIAAAAIQDLYjeRDQMAAJEIAAANAAAAeGwvc3R5bGVzLnht
        bLRWW2+bMBR+n7T/YPmdcilkSQRUTVOkSl01qZ20VwdMYs0XZExEOu2/7xhyIW1XZamWh+BzsL/znXM+28RXreBoTXXNlEyw
        f+FhRGWuCiaXCf7+lDljjGpDZEG4kjTBG1rjq/Tzp7g2G04fV5QaBBCyTvDKmGrqunW+ooLUF6qiEt6USgtiwNRLt640JUVt
        FwnuBp43cgVhEvcIU5GfAiKI/tlUTq5ERQxbMM7MpsPCSOTTu6VUmiw4UG39kOSo9Uc6QK3eBem8r+IIlmtVq9JcAK6rypLl
        9DXdiTtxSX5AAuTzkPzI9YKj3Ft9JlLoarpmtn04jUslTY1y1UiT4GDrSOP6Ga0Jh/Z62E3jXHGlkV4uEpxlXvezbkkE7afd
        EM4Wmlln18ytWzAorXW6NkwfLI0XdtYb+AZUAE3wz4LuItQQgnF+nA840hgab6iWGRhoO37aVBBNgkZ7ht08u/yd2UtNNn4Q
        DRa4XUBISukC9sSukj5UsnelMaelgZQ1W67s06gK/hfKGNBNGheMLJUk3FZpt2I7gHRyyvmj3Tc/yiPstkSyEZkwd0WCYQfa
        +u6GkMJ22OP1hsUfovXYA9gIKP87LGrLPf7fVvvA721S+9WIVBXfZJCFFUBvXXO2lIL2rjQGifUmWinNnmGqFWgO72mvsbY8
        KQGAH9blJQUg+t8pQMPeoXBS3lZUnQxfZe2Hp8jhRdoPjVhQnXUn78fS70QGshpo90i5ew0ie3wk+MHG5HBCbnWEFg3jhsk3
        VAuYRXvYB93RZOzJ3e2QfRSobkFL0nDztH+Z4MP4Ky1YI4L9rG9srUwHkeDD+N5uV39ka0xbc1/D8QVP1GiW4F+3sy+T+W0W
        OGNvNnbCSxo5k2g2d6LwZjafZxMv8G5+D+6PD9we3XUHwvbDac3hjtHbZLcpPh58CR4YPf1OIUB7yH0SjLzryPec7NLznXBE
        xs54dBk5WeQH81E4u42yaMA9OvOW8Vzf7+8rSz6aGiYoZ3LXq12Hhl5oEpjvJOHuOuEeviXSPwAAAP//AwBQSwMEFAAGAAgA
        AAAhAMnJkGQMAQAAEgIAABQAAAB4bC9zaGFyZWRTdHJpbmdzLnhtbHSRQU/DMAyF70j8hyh3lm0wQKjtJIp2Q0ICfoCXmDZS
        6oTYRcCvJwMOqB1Hf0/v+cmutu9DUG+Y2Ueq9Wqx1ArJRuepq/Xz0+7sWisWIAchEtb6A1lvm9OTillU8RLXuhdJN8aw7XEA
        XsSEVJSXmAeQMubOcMoIjntEGYJZL5eXZgBPWtk4kpS9G61G8q8jtr/gQjcV+6aS5j6SxMpIU5kD+IF3yDb7ZEvrqdSCYBez
        h6mwQ9vPYDtGmcFHCC4qh0ENyNOYWwhAFpXznCL5fcBZg0OmajGMAfJRcRb6XUNdmdX6eNgnJBAfAvzjPDebqfEBulj6E48Q
        5udLkAWK+ve0pvy0+QIAAP//AwBQSwMEFAAGAAgAAAAhAFFx6UWqAQAAPwMAABEACAFkb2NQcm9wcy9jb3JlLnhtbCCiBAEo
        oAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIxSTW/bMAy9D9h/MLSzLTv9jJC4w1b0tAIDmqLD
        bqrEJFqtD0h0XAP98ZOt1EmGHnYT+cinx0cubl51k+3AB2XNklRFSTIwwkplNkvyuLrLr0kWkBvJG2tgSXoI5Kb+/GkhHBPW
        w09vHXhUELLIZAITbkm2iI5RGsQWNA9FrDARXFuvOcbQb6jj4oVvgM7K8pJqQC45cjoQ5m5iJHtKKSZK1/pmJJCCQgMaDAZa
        FRU91CJ4HT5sGJGjSq2wd3GmvdxjbikSOFW/BjUVdl1XdGejjKi/or/ufzyMo+bKDF4JIPVCCoYKG6gX9PCMr9A+/wGBKT0F
        ERAeOFqfgCmINr9A31kvQ0ROotgjIQivHMblpb6TRKxueMD7uM21AvmtrxUrvxTrNw36Oa58q9yb4QZbw7+u/U4XLZoCZFtw
        P371T/Owcg87NZxK0nKIpBjNTUOAzKJdLJn7jjydfb9d3ZF6Vs4u83KeV9WqmrPza3Zx9Xuw6KR/sC8l9F78/zPOWXlxxPhO
        UI8XyxE21vdJvpii8ZgNxmt6QI7t3mphP0gdn3z9FwAA//8DAFBLAwQUAAYACAAAACEAH5tdi+8AAACKAQAAEAAIAWRvY1By
        b3BzL2FwcC54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACckE1PwzAMhu9I/Ico
        9zUZSBOa0kzjS1wmOIzdo9TtIlo7SsLU/nsMEwVx5Gb7tR+/ttmMQy9OkHIgrOWy0lIAemoCdrV83T8ubqTIxWHjekKo5QRZ
        buzlhXlJFCGVAFkwAnMtj6XEtVLZH2FwuWIZWWkpDa5wmjpFbRs83JN/HwCLutJ6pWAsgA00izgD5Zm4PpX/Qhvyn/7yYT9F
        NmzNNsY+eFf4SrsLPlGmtoiH0UMvnrEPCEb97jE7h66DZI2aozsaosOJS3P0xPjE02+3LgMLf3ImHs6vtctVpa+1/tryXTPq
        54n2AwAA//8DAFBLAwQUAAYACAAAACEApt4Z85UAAACpAAAAEAAAAHhsL2NhbGNDaGFpbi54bWw8jrEKAjEQRHvBfwjbe3te
        ISJJrhAEe/2AkFtNINkc2SD698bGZuAx8Gb0/M5JvahKLGxgP4ygiH1ZIj8N3G+X3RGUNMeLS4XJwIcEZrvdaO+SPwcXWXUD
        i4HQ2npCFB8oOxnKStybR6nZtY71ibJWcosEopYTTuN4wNwFYLVX1cB1AhX7B1Dpl2g1/kfsFwAA//8DAFBLAQItABQABgAI
        AAAAIQCtStNnbAEAABAFAAATAAAAAAAAAAAAAAAAAAAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhALVV
        MCP0AAAATAIAAAsAAAAAAAAAAAAAAAAApQMAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAGTflBqMAwAA9ggAAA8AAAAA
        AAAAAAAAAAAAygYAAHhsL3dvcmtib29rLnhtbFBLAQItABQABgAIAAAAIQCSB5TsBAEAAD8DAAAaAAAAAAAAAAAAAAAAAIMK
        AAB4bC9fcmVscy93b3JrYm9vay54bWwucmVsc1BLAQItABQABgAIAAAAIQBid2nNQgMAAJcJAAAYAAAAAAAAAAAAAAAAAMcM
        AAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWxQSwECLQAUAAYACAAAACEAwRcQvk4HAADGIAAAEwAAAAAAAAAAAAAAAAA/EAAA
        eGwvdGhlbWUvdGhlbWUxLnhtbFBLAQItABQABgAIAAAAIQDLYjeRDQMAAJEIAAANAAAAAAAAAAAAAAAAAL4XAAB4bC9zdHls
        ZXMueG1sUEsBAi0AFAAGAAgAAAAhAMnJkGQMAQAAEgIAABQAAAAAAAAAAAAAAAAA9hoAAHhsL3NoYXJlZFN0cmluZ3MueG1s
        UEsBAi0AFAAGAAgAAAAhAFFx6UWqAQAAPwMAABEAAAAAAAAAAAAAAAAANBwAAGRvY1Byb3BzL2NvcmUueG1sUEsBAi0AFAAG
        AAgAAAAhAB+bXYvvAAAAigEAABAAAAAAAAAAAAAAAAAAFR8AAGRvY1Byb3BzL2FwcC54bWxQSwECLQAUAAYACAAAACEApt4Z
        85UAAACpAAAAEAAAAAAAAAAAAAAAAAA6IQAAeGwvY2FsY0NoYWluLnhtbFBLBQYAAAAACwALAL4CAAD9IQAAAAA=
"""

}
}
